blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/yourusername/kitchen-pantry-crm/blob/main/README.md
    about: Check the project documentation for setup and usage information
  - name: 💬 Discussions
    url: https://github.com/yourusername/kitchen-pantry-crm/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/yourusername/kitchen-pantry-crm/security/advisories
    about: Report security vulnerabilities privately