#!/bin/bash
# Kitchen Pantry CRM - MCP Development Setup Script
# This script sets up the MCP development environment for Supabase

set -e

echo "🔧 Setting up MCP Development Environment for Kitchen Pantry CRM"
echo "================================================================"

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo "❌ Supabase CLI is not installed. Please install it first."
    exit 1
fi

# Check if Docker is running
if ! docker ps &> /dev/null; then
    echo "❌ Docker is not running. Please start Docker first."
    exit 1
fi

# Navigate to project root
cd "$(dirname "$0")/../.."

echo "📁 Project directory: $(pwd)"

# Start Supabase local development
echo "🚀 Starting Supabase local development environment..."
supabase start

# Wait for services to be ready
echo "⏳ Waiting for services to be ready..."
sleep 10

# Get connection details
echo "🔍 Getting connection details..."
supabase status

# Apply migrations
echo "📊 Applying database migrations..."
supabase db reset --linked=false

# Setup MCP development utilities
echo "🛠️  Setting up MCP development utilities..."

# Create development environment file
cat > .env.development << EOF
# Kitchen Pantry CRM - Development Environment Variables
# Generated by MCP setup script

# Supabase Local Development
SUPABASE_URL=http://127.0.0.1:54321
SUPABASE_ANON_KEY=\$(supabase status --output json | jq -r '.anon_key')
SUPABASE_SERVICE_ROLE_KEY=\$(supabase status --output json | jq -r '.service_role_key')

# Database Connection (for MCP)
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres
DB_HOST=127.0.0.1
DB_PORT=54322
DB_NAME=postgres
DB_USER=postgres
DB_PASSWORD=postgres

# MCP Configuration
MCP_ENVIRONMENT=development
MCP_CONFIG_PATH=./supabase/mcp-config.json
MCP_SECURITY_LEVEL=development_only

# Development Settings
NODE_ENV=development
LOG_LEVEL=debug
API_PORT=3001
EOF

echo "✅ MCP Development environment setup complete!"
echo ""
echo "📝 Next steps:"
echo "1. Source the environment variables: source .env.development"
echo "2. Start the development servers: pnpm dev"
echo "3. Open Supabase Studio: http://127.0.0.1:54323"
echo "4. Use MCP tools for schema management and development"
echo ""
echo "🔧 Available MCP commands:"
echo "- supabase db reset: Reset database with fresh migrations and seed data"
echo "- supabase db diff: Generate migration files from schema changes"
echo "- supabase db push: Push local changes to remote (when ready)"
echo "- supabase gen types typescript: Generate TypeScript types"
echo ""
echo "🔒 Security Note: This setup is for DEVELOPMENT ONLY"
echo "   MCP access is restricted to local development environment"